num_thread: 40
num_game_per_thread: 120
replay_buffer_size: 1024
train_device: cuda:0
act_device: cuda:0
epoch_len: 5000
gamma: 0.999
net: publ-lstm
shuffle_color: 0
target_data_ratio: 2
load_model: ../obl_models/ppo/model0.pthw
llm_prior: openai/meta_prompt5_color/prior.pkl
num_epoch: 150
pikl_beta: 2
pikl_lambda: 0.05
pikl_anneal_epoch: 50
save_per: 50
